/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Lars' at '9/19/17 4:31 PM' with Gradle 2.14.1
 *
 * @author Lars, @date 9/19/17 4:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
